---
title: "R Project Milestone 3"
author: "Moyra Rasheed, Courtney Coon, Jarett Maycott"
date: '2022-10-28'
output:
  pdf_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(dplyr)
library(stringr)
 
```

```{r echo=FALSE, results=FALSE}
# Prep demographic data
## read in data
demo_data<-read.csv(
  "https://raw.githubusercontent.com/PHW290/phw251_projectdata/main/ca_county_demographic.csv",
                    stringsAsFactors = FALSE)

## subset demographic dataset to include only needed columns
demo_sub<-select(demo_data, c("pop12_sqmi", "name", "med_age","renter_occ", "owner_occ"))

## categorize median age: younger is lower priority, older is high priority
sum_med_age<-summary(demo_sub$med_age)
sum_med_age
demo_sub<-demo_sub%>%
  mutate(med_age_CAT= case_when(
    med_age < as.numeric(sum_med_age[2]) ~ "Low priority",      
    med_age < as.numeric(sum_med_age[5]) ~ "Medium priority",
    TRUE ~ "High priority"))%>% 
  mutate(med_age_CAT = factor(med_age_CAT, 
    levels = c("Low priority", "Medium priority", "High priority")))

## categorize pop12_sqmi with low density (rural) as high priority
sum_pop12_sqmi<-summary(demo_sub$pop12_sqmi)
sum_pop12_sqmi
demo_sub<-demo_sub%>%
  mutate(pop12_sqmi_CAT= case_when(
    pop12_sqmi < as.numeric(pop12_sqmi[2]) ~ "High priority",      
    pop12_sqmi < as.numeric(pop12_sqmi[5]) ~ "Medium priority",
    TRUE ~ "Low priority"))%>%
  mutate(pop12_sqmi_CAT = factor(pop12_sqmi_CAT, 
    levels = c("Low priority", "Medium priority", "High priority")))

## create % renter (of all households) variable
demo_sub<-demo_sub%>%
  mutate(renter_ratio=renter_occ/(owner_occ+renter_occ))

## categorize renter_ratio with higher ratio being a higher priority
sum_renter_ratio<-summary(demo_sub$renter_ratio)
sum_renter_ratio
demo_sub<-demo_sub%>%
  mutate(renter_ratio_CAT= case_when(
    renter_ratio < as.numeric(renter_ratio[2]) ~ "Low priority",      
    renter_ratio < as.numeric(renter_ratio[5]) ~ "Medium priority",
    TRUE ~ "High priority"))%>%
  mutate(renter_owner_ratio_CAT = factor(renter_ratio_CAT, 
    levels = c("Low priority", "Medium priority", "High priority")))

demo_col_order <- c("name", "pop12_sqmi", "pop12_sqmi_CAT", "med_age", 
               "med_age_CAT", "renter_ratio", "renter_ratio_CAT")
demo_sub <- demo_sub[, demo_col_order]

```

```{r echo=FALSE, results=FALSE}
# Prep mortality data
mort_data<-read.csv(
  "https://raw.githubusercontent.com/PHW290/phw251_projectdata/main/ca_county_mortality.csv",
                    stringsAsFactors = FALSE,na.strings = "")

## remove last 2 columns b/c mostly NAs ("Annotation_...")
mort_data<-mort_data[,1:8]

## column names are all capitalized
colnames(mort_data) <- str_to_lower(colnames(mort_data))

## filter by 'strata_name' as 'total_population'
mort_sub<-mort_data%>%
  filter(strata_name=="Total Population")
## Note: We kept occurrence and residence data because it's a metric of overall 
## population load at the hospital

## replace NAs with zeros
mort_sub <- mort_sub %>% mutate(count = ifelse(is.na(count), 0, count))

## filter non-chronic diseases
mort_sub<-mort_sub%>%
  filter(cause_desc %in% c("Alzheimer's disease", "Malignant neoplasms",
                     "Chronic lower respiratory diseases","Diabetes mellitus",
                     "Diseases of heart", 
                     "Essential hypertension and hypertensive renal disease",
                     "Chronic liver disease and cirrhosis", 
                     "Nephritis, nephrotic syndrome and nephrosis",
                     "Parkinson's disease", "Cerebrovascular diseases"))
## Note: We removed all non-chronic diseases: "all cause", "assault", 
## "accidents", "influenza" and "self-harm"

## summarize chronic death mortality by county
mort_sub_grouped<-mort_sub%>%
  group_by(county)%>%
  summarize(summed_chronic_dis_mort=sum(count))

## make summed_chronic_dis_mort categorical with higher counts of chronic 
## disease in hospitals being higher priority
sum_summed_chronic_dis_mort<-summary(mort_sub_grouped$summed_chronic_dis_mort)
sum_summed_chronic_dis_mort
mort_sub_grouped<-mort_sub_grouped%>%
  mutate(summed_chronic_dis_mort_CAT= case_when(
    summed_chronic_dis_mort < 
      as.numeric(sum_summed_chronic_dis_mort[2]) ~ "Low priority",      
    summed_chronic_dis_mort < 
      as.numeric(sum_summed_chronic_dis_mort[5]) ~ "Medium priority",
    TRUE ~ "High priority"))%>%
  mutate(summed_chronic_dis_mort_CAT = factor(summed_chronic_dis_mort_CAT, 
    levels = c("Low priority", "Medium priority", "High priority")))

```

```{r echo=FALSE, results=FALSE}
# Prep the healthcare (HCAI) data
healthcare_data<-read.csv(
  "https://raw.githubusercontent.com/PHW290/phw251_projectdata/main/hcai_healthcare_construction.csv",
  stringsAsFactors = FALSE,na.strings = "")

#remove last column ("Collection.of.Counties") b/c mostly NAs
healthcare_data<-healthcare_data[,1:5]

#column names are all capitalized
colnames(healthcare_data) <- str_to_lower(colnames(healthcare_data))

#change "." to "_" for consistency with other data sets
names(healthcare_data) <- gsub(x = names(healthcare_data), pattern = "\\.", 
                               replacement = "_")  

#change county names to match other two data sets (remove numbers in front)
healthcare_data<-healthcare_data%>%
  mutate(county=substring(healthcare_data$county, 6))

## change money column ("Total.Costs...") to numeric
healthcare_data<-healthcare_data%>%
  mutate(total_costs_of_oshpd_projects = total_costs_of_oshpd_projects %>% 
           str_remove_all("[$,]"))
healthcare_data$total_costs_of_oshpd_projects<-
  as.numeric(healthcare_data$total_costs_of_oshpd_projects)

## fix "data_generation_date" (remove empty time)
healthcare_data$data_generation_date<-
  as.Date(healthcare_data$data_generation_date)

## filter data to only include projects with 'project status' as "Pending 
## Construction," "In Construction" or "In Closure"  
healthcare_sub<-healthcare_data%>%
  filter(oshpd_project_status!="In Review")
## Note: We only filtered out "in review" because all other projects with other
## statuses were guaranteed to be completed and we wanted to prioritize 
## locations with the fewest projects that were at any stage of completion

## filter out 2013 and 2014 data so we have 5 yrs of data (from 2015-2020)
healthcare_sub<-healthcare_sub%>%
  filter(data_generation_date > "2015-01-01")

## average 'total_cost' in each category for each county to reduce 
## over-counting that is occurring in the data set
healthcare_sub_grouped<-healthcare_sub%>%
  group_by(county, oshpd_project_status)%>%
  summarize(summed_total_cost=mean(total_costs_of_oshpd_projects))

## R is forcing numbers to be in scientific notation, so fix
options(scipen = 999)

## summarize 'total_cost' of projects 'in closure', 'in construction', 
## or 'pending construction' over the 5 years (2015-2020)
healthcare_sub_grouped<-healthcare_sub%>%
  group_by(county)%>%
  summarize(summed_total_cost=sum(total_costs_of_oshpd_projects))

## make the total cost of all oshpd projects categorical where counties with  
## higher total costs are lower priority
s_summed_total_cost<-summary(healthcare_sub_grouped$summed_total_cost)
s_summed_total_cost
healthcare_sub_grouped<-healthcare_sub_grouped%>%
  mutate(summed_total_cost_CAT= case_when(
    summed_total_cost < as.numeric(s_summed_total_cost[2]) ~ "High priority",      
    summed_total_cost < as.numeric(s_summed_total_cost[5]) ~ "Medium priority",
    TRUE ~ "Low priority"))%>%
  mutate(summed_total_cost_CAT = factor(summed_total_cost_CAT, 
    levels = c("Low priority", "Medium priority", "High priority")))

```


```{r echo=FALSE, results=FALSE}
#merge data sets by county
merged_data<-full_join(mort_sub_grouped, healthcare_sub_grouped, by="county")
merged_data<-full_join(merged_data, demo_sub, by=c("county"= "name"))

```



\newpage
# Table with descriptive stats for variables in data dictionary
```{r}
# library(kableExtra)

# table<-merged_data%>%
#  rowwise() %>%
#  mutate(number_highs= sum(c_across(2:6) == "High priority", na.rm = TRUE),
#         number_mediums= sum(c_across(2:6) == "Medium priority", na.rm = TRUE),
#         temp_rank=(number_highs*2)+number_mediums
#         )%>%
#   ungroup()%>%
#   arrange(desc(temp_rank))%>%
#   select(-c(number_highs, number_mediums,temp_rank))%>%
#   slice(1:10)
# head(table)
# 
# kable(table,
#        col.names = c("County","Chronic disease mortality burden",
#                      "Previous spending on projects", 
#                      "Population density", "Median age of population", 
#                      "% population that are renters"),
#        caption="Top 10 Counties ranked by need for oshpd projects.",
#        booktabs=TRUE, 
#        align='lccccc')%>%
#   kable_styling(latex_options="scale_down")
# 
#  table
```

```{r}
library(ggplot2)
library(ggrepel)
```


```{r}
# Demographic data figure

ggplot(data = merged_data, aes(x = renter_ratio, y = med_age)) + 
geom_point(data = merged_data, aes(x = renter_ratio, y = med_age, 
                                   color = pop12_sqmi_CAT)) +
geom_text_repel(aes(label=ifelse((med_age > 45 & renter_ratio < 0.35), 
                                 county, "")))+
  labs(title = "", x = "ratio of renters to homeowners", 
       y = "median age of county residents", 
       color = "Population per mile^2\n rural as high priority") 

# xlab("ratio of renters to homeowners")+
# ylab("median age of county residents")


```



